### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by Jackelam20** [Jackelam20/prework-study-guide#1]
# HTML

## User Story
As a bootcamp Student
I want the prework notes to be structured on a webpage
so that I can Easily Find and read information

## Acceptance Ciriteria
GIVEN a Prework Study Guide Website
WHEN I visit the website in my browser
THEN I see four Boxes titled HTML, CSS, Git, and JavaScript with associated notes listed

**Comment by JarrettSF** [comment]
Could you be a little more specific, do you simply want a HTML page with four boxes labeled HTML, CSS, Git and Javascript ...Nothing more?
